### ISSUE TITLE
monitoring-plugins fails to build with OpenSSL 4.0

### ISSUE THREAD

**Issue by loqs** [monitoring-plugins/monitoring-plugins#2302]
## monitoring-plugins Version

monitoring-plugins https://github.com/monitoring-plugins/monitoring-plugins/commit/b6021e5e372ba9219684a809e73a20f50e50caca

## System information
Arch Linux Rolling

## Describe the bug
monitoring-plugins fails to build against OpenSSL 4.0 as the `ASN1_STRING` structure has been made opaque and now requires use via access functions.

## Additional information
Steps to reproduce:
```
$ git clone https://github.com/monitoring-plugins/monitoring-plugins.git
$ cd monitoring-plugins
$ autoreconf -fiv
$ ./configure
$ make
....
sslutils.c: In function ‘np_net_ssl_check_certificate’:
sslutils.c:202:27: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  202 |         X509_NAME *subj = X509_get_subject_name(certificate);
      |                           ^~~~~~~~~~~~~~~~~~~~~
sslutils.c:210:9: warning: ‘X509_NAME_get_text_by_NID’ is deprecated: Since OpenSSL 4.0 [-Wdeprecated-declarations]
  210 |         int cnlen = X509_NAME_get_text_by_NID(subj, NID_commonName, cn, sizeof(cn));
      |         ^~~
In file included from common.h:152,
                 from sslutils.c:31:
/usr/include/openssl/x509.h:1041:27: note: declared here
 1041 | OSSL_DEPRECATEDIN_4_0 int X509_NAME_get_text_by_NID(const X509_NAME *name,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
sslutils.c:221:15: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  221 |         if (tm->type == V_ASN1_UTCTIME) {
      |               ^~
sslutils.c:222:23: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  222 |                 if (tm->length < 10) {
      |                       ^~
sslutils.c:226:36: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  226 |                 stamp.tm_year = (tm->data[0] - '0') * 10 + (tm->data[1] - '0');
      |                                    ^~
sslutils.c:226:63: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  226 |                 stamp.tm_year = (tm->data[0] - '0') * 10 + (tm->data[1] - '0');
      |                                                               ^~
sslutils.c:233:23: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  233 |                 if (tm->length < 12) {
      |                       ^~
sslutils.c:237:36: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  237 |                 stamp.tm_year = (tm->data[0] - '0') * 1000 + (tm->data[1] - '0') * 100 +
      |                                    ^~
sslutils.c:237:65: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  237 |                 stamp.tm_year = (tm->data[0] - '0') * 1000 + (tm->data[1] - '0') * 100 +
      |                                                                 ^~
sslutils.c:238:52: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  238 |                                                 (tm->data[2] - '0') * 10 + (tm->data[3] - '0');
      |                                                    ^~
sslutils.c:238:79: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  238 |                                                 (tm->data[2] - '0') * 10 + (tm->data[3] - '0');
      |                                                                               ^~
sslutils.c:242:27: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  242 |         stamp.tm_mon = (tm->data[2 + offset] - '0') * 10 + (tm->data[3 + offset] - '0') - 1;
      |                           ^~
sslutils.c:242:63: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  242 |         stamp.tm_mon = (tm->data[2 + offset] - '0') * 10 + (tm->data[3 + offset] - '0') - 1;
      |                                                               ^~
sslutils.c:243:28: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  243 |         stamp.tm_mday = (tm->data[4 + offset] - '0') * 10 + (tm->data[5 + offset] - '0');
      |                            ^~
sslutils.c:243:64: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  243 |         stamp.tm_mday = (tm->data[4 + offset] - '0') * 10 + (tm->data[5 + offset] - '0');
      |                                                                ^~
sslutils.c:244:28: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  244 |         stamp.tm_hour = (tm->data[6 + offset] - '0') * 10 + (tm->data[7 + offset] - '0');
      |                            ^~
sslutils.c:244:64: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  244 |         stamp.tm_hour = (tm->data[6 + offset] - '0') * 10 + (tm->data[7 + offset] - '0');
      |                                                                ^~
sslutils.c:245:27: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  245 |         stamp.tm_min = (tm->data[8 + offset] - '0') * 10 + (tm->data[9 + offset] - '0');
      |                           ^~
sslutils.c:245:63: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  245 |         stamp.tm_min = (tm->data[8 + offset] - '0') * 10 + (tm->data[9 + offset] - '0');
      |                                                               ^~
sslutils.c:246:27: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  246 |         stamp.tm_sec = (tm->data[10 + offset] - '0') * 10 + (tm->data[11 + offset] - '0');
      |                           ^~
sslutils.c:246:64: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  246 |         stamp.tm_sec = (tm->data[10 + offset] - '0') * 10 + (tm->data[11 + offset] - '0');
      |                                                                ^~
sslutils.c: In function ‘np_net_ssl_get_cert_expiration’:
sslutils.c:329:27: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  329 |         X509_NAME *subj = X509_get_subject_name(certificate);
      |                           ^~~~~~~~~~~~~~~~~~~~~
sslutils.c:338:9: warning: ‘X509_NAME_get_text_by_NID’ is deprecated: Since OpenSSL 4.0 [-Wdeprecated-declarations]
  338 |         int cnlen = X509_NAME_get_text_by_NID(subj, NID_commonName, cn, sizeof(cn));
      |         ^~~
/usr/include/openssl/x509.h:1041:27: note: declared here
 1041 | OSSL_DEPRECATEDIN_4_0 int X509_NAME_get_text_by_NID(const X509_NAME *name,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
sslutils.c:349:33: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  349 |         if (expiration_timestamp->type == V_ASN1_UTCTIME) {
      |                                 ^~
sslutils.c:350:41: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  350 |                 if (expiration_timestamp->length < 10) {
      |                                         ^~
sslutils.c:356:46: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  356 |                         (expiration_timestamp->data[0] - '0') * 10 + (expiration_timestamp->data[1] - '0');
      |                                              ^~
sslutils.c:356:91: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  356 |                         (expiration_timestamp->data[0] - '0') * 10 + (expiration_timestamp->data[1] - '0');
      |                                                                                           ^~
sslutils.c:362:41: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  362 |                 if (expiration_timestamp->length < 12) {
      |                                         ^~
sslutils.c:367:54: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  367 |                 stamp.tm_year = (expiration_timestamp->data[0] - '0') * 1000 +
      |                                                      ^~
sslutils.c:368:70: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  368 |                                                 (expiration_timestamp->data[1] - '0') * 100 +
      |                                                                      ^~
sslutils.c:369:70: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  369 |                                                 (expiration_timestamp->data[2] - '0') * 10 +
      |                                                                      ^~
sslutils.c:370:70: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  370 |                                                 (expiration_timestamp->data[3] - '0');
      |                                                                      ^~
sslutils.c:374:45: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  374 |         stamp.tm_mon = (expiration_timestamp->data[2 + offset] - '0') * 10 +
      |                                             ^~
sslutils.c:375:57: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  375 |                                    (expiration_timestamp->data[3 + offset] - '0') - 1;
      |                                                         ^~
sslutils.c:376:46: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  376 |         stamp.tm_mday = (expiration_timestamp->data[4 + offset] - '0') * 10 +
      |                                              ^~
sslutils.c:377:62: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  377 |                                         (expiration_timestamp->data[5 + offset] - '0');
      |                                                              ^~
sslutils.c:378:46: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  378 |         stamp.tm_hour = (expiration_timestamp->data[6 + offset] - '0') * 10 +
      |                                              ^~
sslutils.c:379:62: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  379 |                                         (expiration_timestamp->data[7 + offset] - '0');
      |                                                              ^~
sslutils.c:380:45: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  380 |         stamp.tm_min = (expiration_timestamp->data[8 + offset] - '0') * 10 +
      |                                             ^~
sslutils.c:381:57: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  381 |                                    (expiration_timestamp->data[9 + offset] - '0');
      |                                                         ^~
sslutils.c:382:45: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  382 |         stamp.tm_sec = (expiration_timestamp->data[10 + offset] - '0') * 10 +
      |                                             ^~
sslutils.c:383:57: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  383 |                                    (expiration_timestamp->data[11 + offset] - '0');
      |                                                         ^~
sslutils.c: In function ‘mp_net_ssl_check_certificate’:
sslutils.c:470:27: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  470 |         X509_NAME *subj = X509_get_subject_name(certificate);
      |                           ^~~~~~~~~~~~~~~~~~~~~
sslutils.c:479:9: warning: ‘X509_NAME_get_text_by_NID’ is deprecated: Since OpenSSL 4.0 [-Wdeprecated-declarations]
  479 |         int cnlen = X509_NAME_get_text_by_NID(subj, NID_commonName, commonName, sizeof(commonName));
      |         ^~~
/usr/include/openssl/x509.h:1041:27: note: declared here
 1041 | OSSL_DEPRECATEDIN_4_0 int X509_NAME_get_text_by_NID(const X509_NAME *name,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
sslutils.c:490:29: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  490 |         if (expiry_timestamp->type == V_ASN1_UTCTIME) {
      |                             ^~
sslutils.c:491:37: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  491 |                 if (expiry_timestamp->length < 10) {
      |                                     ^~
sslutils.c:497:50: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  497 |                 stamp.tm_year = (expiry_timestamp->data[0] - '0') * 10 + (expiry_timestamp->data[1] - '0');
      |                                                  ^~
sslutils.c:497:91: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  497 |                 stamp.tm_year = (expiry_timestamp->data[0] - '0') * 10 + (expiry_timestamp->data[1] - '0');
      |                                                                                           ^~
sslutils.c:504:37: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  504 |                 if (expiry_timestamp->length < 12) {
      |                                     ^~
sslutils.c:509:50: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  509 |                 stamp.tm_year = (expiry_timestamp->data[0] - '0') * 1000 +
      |                                                  ^~
sslutils.c:510:66: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  510 |                                                 (expiry_timestamp->data[1] - '0') * 100 +
      |                                                                  ^~
sslutils.c:511:66: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  511 |                                                 (expiry_timestamp->data[2] - '0') * 10 + (expiry_timestamp->data[3] - '0');
      |                                                                  ^~
sslutils.c:511:107: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  511 |                                                 (expiry_timestamp->data[2] - '0') * 10 + (expiry_timestamp->data[3] - '0');
      |                                                                                                           ^~
sslutils.c:516:41: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  516 |         stamp.tm_mon = (expiry_timestamp->data[2 + offset] - '0') * 10 +
      |                                         ^~
sslutils.c:517:53: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  517 |                                    (expiry_timestamp->data[3 + offset] - '0') - 1;
      |                                                     ^~
sslutils.c:518:42: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  518 |         stamp.tm_mday = (expiry_timestamp->data[4 + offset] - '0') * 10 +
      |                                          ^~
sslutils.c:519:58: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  519 |                                         (expiry_timestamp->data[5 + offset] - '0');
      |                                                          ^~
sslutils.c:520:42: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  520 |         stamp.tm_hour = (expiry_timestamp->data[6 + offset] - '0') * 10 +
      |                                          ^~
sslutils.c:521:58: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  521 |                                         (expiry_timestamp->data[7 + offset] - '0');
      |                                                          ^~
sslutils.c:522:41: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  522 |         stamp.tm_min = (expiry_timestamp->data[8 + offset] - '0') * 10 +
      |                                         ^~
sslutils.c:523:53: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  523 |                                    (expiry_timestamp->data[9 + offset] - '0');
      |                                                     ^~
sslutils.c:524:41: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  524 |         stamp.tm_sec = (expiry_timestamp->data[10 + offset] - '0') * 10 +
      |                                         ^~
sslutils.c:525:53: error: invalid use of incomplete typedef ‘ASN1_STRING’ {aka ‘struct asn1_string_st’}
  525 |                                    (expiry_timestamp->data[11 + offset] - '0');
      |                                                     ^~
....
```
[monitoring-plugins-openssl-4.0-build-failure.log](https://github.com/user-attachments/files/30368635/monitoring-plugins-openssl-4.0-build-failure.log)

@pierres

**Comment by loqs** [comment]
@RincewindsHat would a pull request replacing direct access with function use or refactoring to use `ASN1_TIME_to_tm` instead of custom time conversion code be helpful?

**Comment by RincewindsHat** [comment]
Hi, thank you for report. Yes, a fix would of course be very welcome.
Sorry for the lack of response, there is not enough time for all the good things :-)

**Comment by loqs** [comment]
Sorry for the delay writing tests to try and cover all the branches in the time conversion code took some time. I also added code to test as much of the rest of sslutils as possible without mocking or a controlled SSL server available.
