### ISSUE TITLE
check_dns  does not compile on Debian 3.1 [sf#1412721]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#538]
Submitted by sakari on 2006-01-23 12:09:11

Debian does not have nslookup, they use the package host instead. 
When compiling the nagios-plugins-HEAD-200601230052, compilation 
of check_dns fails with the following error:

check_dns.c: In function `main':
check_dns.c:81: error:`NSLOOKUP_COMMAND' undeclared (first use in 
this function)
check_dns.c:81: error: (Each undeclared identifier is reported only once
check_dns.c:81: error: for each function it appears in.)
make[2]: **\* [check_dns.o] Error 1
make[2]: Leaving directory `/tmp/nagios-plugins-HEAD-200601230052/
plugins'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/tmp/nagios-plugins-HEAD-200601230052'
make: **\* [all] Error 2

Version 1.4.2 of nagios-plugins compiles on this system, and it does 
warn about nslookup missing when running ./configure. The HEAD 
version does not warn about nslookup missing.
