### ISSUE TITLE
check_smtp.c in 1.4.3 fails to compile on Solaris 2.6 [sf#1484822]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#711]
Submitted by duncan_ferguson on 2006-05-09 18:31:18

make[3]: Entering directory
`/tmp/nagios-plugins-1.4.3/plugins'
if gcc
-DLOCALEDIR=\"/home/loki/fergusod/cvsroot/nagios2/shared/egg-nagioscl/package/usr/local/nagios2/share/locale\"
-DHAVE_CONFIG_H -I. -I. -I.. -I.. -I../lib -I../intl  
   -Wall -g -O2 -MT check_smtp.o -MD -MP -MF
".deps/check_smtp.Tpo" -c -o check_smtp.o check_smtp.c; \
then mv -f ".deps/check_smtp.Tpo"
".deps/check_smtp.Po"; else rm -f
".deps/check_smtp.Tpo"; exit 1; fi
check_smtp.c: In function`main':
check_smtp.c:179: warning: implicit declaration of
function `gethostbyname'
check_smtp.c:179: warning: assignment makes pointer
from integer without a cast
check_smtp.c:181: error: dereferencing pointer to
incomplete type
make[3]: *** [check_smtp.o] Error 1
make[3]: Leaving directory
`/tmp/nagios-plugins-1.4.3/plugins'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory
`/tmp/nagios-plugins-1.4.3/plugins'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/tmp/nagios-plugins-1.4.3'
make: **\* [all] Error 2
